import { Link } from 'react-router-dom';
import { m } from 'framer-motion';
import LandingNav from '../components/LandingNav.jsx';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white flex flex-col font-body">
      <LandingNav />
      
      <section className="flex-1 pt-24 sm:pt-32 pb-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <m.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
          >
            {/* Header */}
            <div className="text-center mb-12">
              <h1 className="text-4xl sm:text-5xl font-bold text-white mb-4 font-display tracking-tight">
                Terms & Conditions
              </h1>
            </div>

            {/* Content */}
            <div className="prose prose-invert max-w-none">
              <div className="rounded-2xl p-8 bg-white/[0.03] border border-white/[0.08] space-y-6">
                
                <div className="space-y-4">
                  <p className="text-white/70 leading-relaxed">
                    1. This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                  </p>

                  <p className="text-white/70 leading-relaxed">
                    2. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name obula.io ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
                  </p>

                  <p className="text-white/70 leading-relaxed">
                    3. The Platform is owned by ZYPIT PRIVATE LIMITED, a company incorporated under the Companies Act, 1956 with its registered office at 1383, 3rd floor, 1st stage,5th block HBR Layout, Bangalore, Karnataka, India 560045 (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our')..
                  </p>

                  <p className="text-white/70 leading-relaxed">
                    4. Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services'). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason.
                  </p>

                  <p className="text-white/70 leading-relaxed">
                    5. By using our Platform, you agree to provide accurate and complete information when creating an account, maintain the security of your account credentials, and comply with all applicable laws and regulations.
                  </p>

                  <p className="text-white/70 leading-relaxed">
                    6. The Platform Owner does not accept any responsibility for any loss or damage that may result from your use of the Platform or Services.
                  </p>

                  <p className="text-white/70 leading-relaxed">
                    7. The Platform Owner reserves the right to modify, suspend, or discontinue any aspect of the Platform or Services at any time.
                  </p>

                  <p className="text-white/70 leading-relaxed">
                    8. The Platform Owner reserves the right to terminate or suspend your access to the Platform immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
                  </p>

                  <p className="text-white/70 leading-relaxed">
                    9. These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts in India.
                  </p>

                  <p className="text-white/70 leading-relaxed">
                    10. You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
                  </p>

                  <p className="text-white/70 leading-relaxed">
                    11. Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
                  </p>

                  <p className="text-white/70 leading-relaxed">
                    12. These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.
                  </p>

                  <p className="text-white/70 leading-relaxed">
                    13. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in and .
                  </p>

                  <p className="text-white/70 leading-relaxed">
                    14. All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
                  </p>
                </div>

              </div>
            </div>

            {/* Back to Home */}
            <div className="mt-12 text-center">
              <Link 
                to="/" 
                className="inline-flex items-center gap-2 text-white/60 hover:text-white transition-colors"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                </svg>
                Back to Home
              </Link>
            </div>
          </m.div>
        </div>
      </section>
    </div>
  );
}
